name: Frontend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    ci:
      runs-on: ubuntu-latest
      container:
        image: node

      steps:
        - uses: actions/checkout@v1
        - name: Install & Tests
          run: |
            npm install
            npm test
    cd:
          runs-on: ubuntu-latest
          needs: ci

          steps:
            - uses: actions/checkout@v1
            - name: Docker login
              run: docker login -u ${{ secrets.Docker_User }} -p ${{ secrets.Docker_Password }}
            - name: Build
              run: docker build -t front .
            - name: Tags
              run: |
                 docker tag front ${{ secrets.Docker_User }}/front:${{ github.sha }}
                 docker tag front ${{ secrets.Docker_User }}/front:latest
            - name: Push
              run: |
                 docker push ${{ secrets.Docker_User }}/front:${{ github.sha }}
                 docker push ${{ secrets.Docker_User }}/front:latest
